name: app_couteau
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  http: ^0.13.3
  url_launcher: ^6.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/img/

